-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."consolidated_mastodon" add column "source" text
--  not null default 'twitter';
